### ISSUE TITLE
[Question] OLM, exposing metrics

### ISSUE THREAD

**Issue by agrrh** [medik8s/self-node-remediation#196]
Hello!

I was able to install self-node-remediation via OLM and asking for help now.

I'd like to access metrics, but metrics endpoint listens to `127.0.0.1:8080` so they are unreachable for prometheus instance. This value is set with `args` in `Deployment`.

I could set `metrics-bind-address` to `:8080` with `Subscription` `spec.config`, but args value has the priorirty.

Is it on purpose?
What's the proper/proposed way to deal with it?

Thank you.

**Comment by slintes** [comment]
Hello @agrrh, thanks for reaching out. There should be another container running (kube-rbac-proxy), serving the metrics and handling RBAC and potentially TLS. We need to investigate why it's missing in our deployment. We will get back to you soon.

**Comment by mshitrit** [comment]
Also feel free to use our Google Group/mail medik8s@googlegroups.com to contact us with any more questions
